package lab1.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.PERSONAL_CODE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private Integer personalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.SURNAME
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @return the value of PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @param name the value for PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.PERSONAL_CODE
     *
     * @return the value of PUBLIC.CUSTOMER.PERSONAL_CODE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public Integer getPersonalCode() {
        return personalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.PERSONAL_CODE
     *
     * @param personalCode the value for PUBLIC.CUSTOMER.PERSONAL_CODE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setPersonalCode(Integer personalCode) {
        this.personalCode = personalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.SURNAME
     *
     * @return the value of PUBLIC.CUSTOMER.SURNAME
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.SURNAME
     *
     * @param surname the value for PUBLIC.CUSTOMER.SURNAME
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}