package lab1.mybatis.model;

public class CustomerSale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER_SALE.CUSTOMERS_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private Integer customersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER_SALE.SALES_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private Integer salesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER_SALE.CUSTOMERS_ID
     *
     * @return the value of PUBLIC.CUSTOMER_SALE.CUSTOMERS_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public Integer getCustomersId() {
        return customersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER_SALE.CUSTOMERS_ID
     *
     * @param customersId the value for PUBLIC.CUSTOMER_SALE.CUSTOMERS_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setCustomersId(Integer customersId) {
        this.customersId = customersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER_SALE.SALES_ID
     *
     * @return the value of PUBLIC.CUSTOMER_SALE.SALES_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public Integer getSalesId() {
        return salesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER_SALE.SALES_ID
     *
     * @param salesId the value for PUBLIC.CUSTOMER_SALE.SALES_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setSalesId(Integer salesId) {
        this.salesId = salesId;
    }
}