package lab1.mybatis.model;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.SALE_CODE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private String saleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.SALE_STATUS
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private String saleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.SHOP_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.ID
     *
     * @return the value of PUBLIC.SALE.ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.ID
     *
     * @param id the value for PUBLIC.SALE.ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.SALE_CODE
     *
     * @return the value of PUBLIC.SALE.SALE_CODE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public String getSaleCode() {
        return saleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.SALE_CODE
     *
     * @param saleCode the value for PUBLIC.SALE.SALE_CODE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setSaleCode(String saleCode) {
        this.saleCode = saleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.SALE_STATUS
     *
     * @return the value of PUBLIC.SALE.SALE_STATUS
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public String getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.SALE_STATUS
     *
     * @param saleStatus the value for PUBLIC.SALE.SALE_STATUS
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setSaleStatus(String saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.SHOP_ID
     *
     * @return the value of PUBLIC.SALE.SHOP_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.SHOP_ID
     *
     * @param shopId the value for PUBLIC.SALE.SHOP_ID
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}