package lab1.mybatis.dao;

import java.util.List;
import lab1.mybatis.model.CustomerSale;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CustomerSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    int insert(CustomerSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CUSTOMER_SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    List<CustomerSale> selectAll();
}