package lab1.mybatis.dao;

import java.util.List;
import lab1.mybatis.model.Sale;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    Sale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    List<Sale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Sun Mar 31 13:42:53 EEST 2019
     */
    int updateByPrimaryKey(Sale record);
}